### ISSUE TITLE
Add Docker support to the repo

### ISSUE THREAD

**Issue by ganeshpatil386386** [hoppscotch/docs#230]
Hey HoppScotch Team,
The idea is to add **Docker support** to the repo for quick and easy contributor setup. 
Meanwhile, The setup of the repo is straightforward with **Mintlify**.

I recently faced an issue with the **Node version** while setting up the docs repo on my local machine that's why this could be a better solution. I'm not sure if this is something the Hoppscothch team is looking for as a contribution, but I'm happy to work on this issue. 

@liyasthomas @SanskritiHarmukh @thetronjohnson

**Comment by SanskritiHarmukh** [comment]
Hey @ganeshpatil386386 , thank you for your suggestion. At the moment, we're not planning to proceed with this idea because we believe containerizing the repo isn’t a necessary step right now. Most of the documentation updates are handled by the team, and the repo currently has a relatively small number of contributors. However, we’ll definitely consider revisiting this idea if the need arises in the future.
